// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBV1sq_cJY6coSfXCMYUDvZKcqpF4brzs',
    appId: '1:753507618735:web:f8f62ab571eb225077695a',
    messagingSenderId: '753507618735',
    projectId: 'president-bc5e7',
    authDomain: 'president-bc5e7.firebaseapp.com',
    databaseURL: 'https://president-bc5e7-default-rtdb.firebaseio.com',
    storageBucket: 'president-bc5e7.firebasestorage.app',
    measurementId: 'G-1B4GJ70G1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCir0NwZ2AcrAg-0br6REGwCYQT0s1uEhA',
    appId: '1:753507618735:android:6a237e128c474e3977695a',
    messagingSenderId: '753507618735',
    projectId: 'president-bc5e7',
    databaseURL: 'https://president-bc5e7-default-rtdb.firebaseio.com',
    storageBucket: 'president-bc5e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG9Jdf05p3IKIQWmcBHJcbXU3gJY9CD1E',
    appId: '1:753507618735:ios:49f2194ab906242277695a',
    messagingSenderId: '753507618735',
    projectId: 'president-bc5e7',
    databaseURL: 'https://president-bc5e7-default-rtdb.firebaseio.com',
    storageBucket: 'president-bc5e7.firebasestorage.app',
    iosClientId: '753507618735-q9pcvi53826q37vpc29pqu6kvigciacm.apps.googleusercontent.com',
    iosBundleId: 'com.president.app.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG9Jdf05p3IKIQWmcBHJcbXU3gJY9CD1E',
    appId: '1:753507618735:ios:49f2194ab906242277695a',
    messagingSenderId: '753507618735',
    projectId: 'president-bc5e7',
    databaseURL: 'https://president-bc5e7-default-rtdb.firebaseio.com',
    storageBucket: 'president-bc5e7.firebasestorage.app',
    iosClientId: '753507618735-q9pcvi53826q37vpc29pqu6kvigciacm.apps.googleusercontent.com',
    iosBundleId: 'com.president.app.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBV1sq_cJY6coSfXCMYUDvZKcqpF4brzs',
    appId: '1:753507618735:web:83253c1b604f112877695a',
    messagingSenderId: '753507618735',
    projectId: 'president-bc5e7',
    authDomain: 'president-bc5e7.firebaseapp.com',
    databaseURL: 'https://president-bc5e7-default-rtdb.firebaseio.com',
    storageBucket: 'president-bc5e7.firebasestorage.app',
    measurementId: 'G-QG80JXSZ48',
  );
}
